name: Comprehensive ZAP Security Scan

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 3 * * 1'  # Monday 3 AM

jobs:
  setup:
    name: Build and Deploy App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build application
        run: mvn clean package -DskipTests

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

  baseline-scan:
    name: ZAP Baseline Scan
    needs: setup
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v5

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: target/

      - name: Build Docker image
        run: docker build -t cicd-demo:test .

      - name: Run application
        run: |
          docker run -d -p 5000:5000 --name app cicd-demo:test
          timeout 60 bash -c 'until curl -f http://localhost:5000/; do sleep 2; done'

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:5000'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

      - name: Cleanup
        if: always()
        run: docker stop app && docker rm app

  full-scan:
    name: ZAP Full Scan
    needs: setup
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'

    steps:
      - uses: actions/checkout@v5

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: target/

      - name: Build Docker image
        run: docker build -t cicd-demo:test .

      - name: Run application
        run: |
          docker run -d -p 5000:5000 --name app cicd-demo:test
          timeout 60 bash -c 'until curl -f http://localhost:5000/; do sleep 2; done'

      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          target: 'http://localhost:5000'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -j'

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-full-report
          path: |
            report_html.html
            report_json.json
            report_md.md

      - name: Cleanup
        if: always()
        run: docker stop app && docker rm app