name: ZAP Baseline Scan

on:
  push

permissions:
  contents: read
  issues: write

jobs:
  zap-baseline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build application
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t cicd-demo:test .

      - name: Run application
        run: |
          docker run -d -p 5000:5000 --name app cicd-demo:test
          echo "Waiting for application to start..."
          timeout 120 bash -c 'until curl -f http://localhost:5000/ > /dev/null 2>&1; do echo "Waiting..."; sleep 3; done'
          echo "Application started successfully"
          
      - name: Verify application endpoints
        run: |
          curl -v http://localhost:5000/
          curl -v http://localhost:5000/robots.txt

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:5000'
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_action: false
          cmd_options: '-a -d -P 61010 -l WARN'

      - name: Cleanup
        if: always()
        run: docker stop app && docker rm app